image: nfcore/gitpod:latest

vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - EditorConfig.EditorConfig              # override user/workspace settings with settings found in .editorconfig files
    - Gruntfuggly.todo-tree                  # Display TODO and FIXME in a tree view in the activity bar
    - mechatroner.rainbow-csv                # Highlight columns in csv files in different colors
    # - nextflow.nextflow                      # Nextflow syntax highlighting
    - oderwat.indent-rainbow                 # Highlight indentation level

ports:
- port: 8080
  onOpen: ignore
tasks:
- init: git checkout gitpod_exercises
- command: |
        parsed=`echo $url | tr -s "[" "/" | tr -s "+" "."`
        newurl="https://$parsed"
        sleep 10
        gp preview $newurl
