repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-svelte@^3.1.2
          - prettier-plugin-astro@^0.12.3
        exclude: pnpm-lock.yaml
        files: \.(astro|svelte|mdx|md|yml|yaml)$
