version: "3.8"
services:
    db:
      image: mysql:8.0
      ports:
        - 3306:3306
      environment: 
        - MYSQL_ROOT_PASSWORD=typist0tulip7console-PIMENTO4cosmic
        - MYSQL_DATABASE=nfcore
        - MYSQL_USER=nfcore_admin
        - MYSQL_PASSWORD=PEBBLY8exhibit_mead1cilium6despise
      volumes:
        - "/var/lib/mysql:/var/lib/mysql"
    web:
        image: webdevops/php-apache:7.4
        container_name: web
        restart: always
        environment:
          - WEB_DOCUMENT_ROOT=/var/www/public_html
        volumes:
          - .:/var/www/
        ports:
          - "8888:80"
        depends_on: 
          - db
    
      
