name: Add Netlify Link to PR

on:
  pull_request:
    paths:
      - 'src/pages/**'

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check for changed files
        id: changed-files
        uses: tj-actions/changed-files@v43

      - name: Add Netlify link to PR
        if: steps.changed-files.outputs.all_changed_files != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const changedFiles = `${{ steps.changed-files.outputs.all_changed_files }}`.split('\n');
            console.log('Changed files:', changedFiles)
            const netlifyLinks = changedFiles
              .filter(file => file.startsWith('src/pages/'))
              .map(file => `@netlify ${file?.replace('src/pages/', '/')}`)[0]
              ?.replace(/\.md$/, '').replace(/\.mdx$/, '').replace(/\/index$/, '');

            if (netlifyLinks) {
              const { data: pullRequest } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
              });

              const currentBody = pullRequest.body || '';
              if (currentBody.includes('@netlify')) {
                return; // Skip if the PR body already contains a Netlify link
              }
              const newBody = `${currentBody}\n\n${netlifyLinks}`;

              // Update the pull request body
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequest.number,
                body: newBody,
              });
            }
