name: Open PR with tools API docs based on webhook call
on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'The name of the release branch'
        required: true
        default: 'dev'

jobs:
  api-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout tools code
        uses: actions/checkout@v4
        with:
          repository: 'nf-core/tools'
          ref: ${{ inputs.ref_name }}
          path: 'tools'

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install remark unist-util-visit

      - name: run API generation script
        run: |
          cd tools
          bash docs/api/generate-api-docs.sh --release ${{ inputs.ref_name }}

      # Install and run pre-commit
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: 3.11

      # install prettier plugins
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: 20

      - run: npm install --only=dev

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        id: pre-commit
        run: pre-commit run --all-files
        continue-on-error: true

      - name: Commit & push changes
        id: commit-and-push
        run: |
          git config user.email "core@nf-co.re"
          git config user.name "nf-core-bot"
          git config push.default upstream
          git add .
          git status
          git commit -m "[automated] Update nf-core/tools API docs for ${{ inputs.ref_name }}"
          git push

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update nf-core/tools API docs for ${{github.ref_name}}
          title: Update nf-core/tools API docs for ${{github.ref_name}}
          body: |
            This PR updates the nf-core/tools API docs for ${{github.ref_name}}.
            Please review the changes and merge if they look good.
          branch: 'update-api-docs-${{github.ref_name}}'
          delete-branch: true
          base: 'main'
          draft: false
