name: Generate images for docs
on:
  workflow_dispatch:
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: 3.x

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@561fcfc7146dcb12e3871909b635ab092a781f34 # v2

      - name: Install nf-core/tools
        run: pip install nf-core

      - name: Generate terminal images with rich-codex
        # Change back to @v1 when v1.2.7 is released
        uses: ewels/rich-codex@main
        env:
          COLUMNS: 100
          HIDE_PROGRESS: 'true'
          NXF_ANSI_LOG: false
        with:
          commit_changes: 'true'
          terminal_width: 100
          skip_git_checks: 'true'
